### ISSUE TITLE
Signature invalid but can successfully request in POSTMAN

### ISSUE THREAD

**Issue by achadee** [notEthan/oauthenticator#22]
Hi I am currently having a issue with faraday and this middleware thats making me scratch my head:
https://github.com/lostisland/faraday/issues/655

Any help at all will be greatly appreciated!

**Comment by notEthan** [comment]
hmm. that's not a lot of information to go on, and invalid signature errors can be particularly tricky to debug. if it's working in postman, that's good information.

is the "add params to header" field checked in postman? if it isn't, then the oauth params go into the query instead of the Authorization header, which isn't a style that this gem currently supports - it shouldn't be terribly hard to add that, but I haven't had any need for it.

you mention URL encoding / double encoding, which is an issue I have had with other oauth clients in conjunction with an invalid signature. I have gone to significant lengths to ensure this gem does its encoding in accordance with the spec. when you use postman, is the "encode oauth signature" box checked?

if you have access to the server doing the calculation, and it is possible to add debug code, then comparing the signature base that's calculated by the server and the one calculated by this client would be most informative. you can see the signature base for a request by either:
- easy way, I think, would be to monkey-patch the method `OAuthenticator::SignableRequest#signature_base` (https://github.com/notEthan/oauthenticator/blob/v1.3.3/lib/oauthenticator/signable_request.rb#L167-L173) something like:
```ruby
class OAuthenticator::SignableRequest
  alias :real_signature_base :signature_base
  def signature_base
    puts real_signature_base
    real_signature_base
  end
end
```
- without monkey-patching, constructing a `OAuthenticator::SignableRequest` object sort of by hand with the same params it would get from faraday:
```ruby
oauthenticator_signable_request = OAuthenticator::SignableRequest.new(
  :request_method => my_request_method,
  :uri => my_request_uri,
  :media_type => my_request_media_type,
  :body => my_request_body,
  :signature_method => my_oauth_signature_method,
  :consumer_key => my_oauth_consumer_key,
  :consumer_secret => my_oauth_consumer_secret,
  :token => my_oauth_token,
  :token_secret => my_oauth_token_secret,
  :realm => my_authorization_realm
)
puts oauthenticator_signable_request.send(:signature_base)
```

you probably don't need all those params, see http://www.rubydoc.info/gems/oauthenticator/OAuthenticator/SignableRequest#initialize-instance_method for what's actually required 

then comparing that string to the signature base generated on the server, you should be able to see if anything looks different, is encoded differently, anything that would cause the hash that constructs the signature to end up with a different value

**Comment by notEthan** [comment]
another thing occurs to me: oauthenticator supports, and, by default enables, the [OAuth Request Body Hash](https://tools.ietf.org/html/draft-eaton-oauth-bodyhash-00)
specification. this is not widely supported though - it is in theory compatible with a server that doesn't support it, but in practice many servers would not include the unrecognized field `oauth_body_hash` in the signature and therefore calculate a different signature. you could try passing the option `:hash_body? => false` to faraday to see if that results in a matching signature.

**Comment by notEthan** [comment]
closing; feel free to reopen if this is still an issue @achadee
